baseurl: /wastwrites
title: Wast Writes
subtitle: A Collection of Short Stories
author: Wast Writes
simple_search: http://google.com/search
description: A beautiful collection of short stories, styled with the elegant Tufte aesthetic
name: wastwrites
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md', 'SETUP_INSTRUCTIONS.md', 'vendor/', 'node_modules/', '.bundle/']

# Collections for story categories
collections:
  pure-human:
    output: true
    permalink: /stories/:name/
  human-ai:
    output: true  
    permalink: /stories/:name/
  pure-ai:
    output: true
    permalink: /stories/:name/

post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/
